### Get all films
GET http://localhost:8083/api/films

### Get single film
GET http://localhost:8083/api/films/da129c31-4e55-424a-958d-29bdb864369a

### Get all films from category
GET http://localhost:8083/api/categories/58dadcf0-8a5c-46dd-8522-2ccf2714be80/films

###  Put new film to Sci-Fi category
PUT http://localhost:8083/api/films/e58c030e-f03f-4270-848b-dd6cada54ff2
Content-Type: application/json

{
"name": "Test",
"productionYear": 2010,
"filmCategory": "58dadcf0-8a5c-46dd-8522-2ccf2714be80"
}

###  Put new film to not-existing category
PUT http://localhost:8083/api/films/e58c030e-f03f-4270-848b-dd6cada54ff2
Content-Type: application/json

{
"name": "Test",
"productionYear": 2010,
"filmCategory": "58dadcf0-8a5c-46dd-8522-2ccf2711be80"
}

###  Update film productionYear
PATCH http://localhost:8083/api/films/da129c31-4e55-424a-958d-29bdb864369a
Content-Type: application/json

{
"productionYear": 1999
}

###  Delete film
DELETE http://localhost:8083/api/films/e58c030e-f03f-4270-848b-dd6cada54ff2

###  Get all film categories
GET http://localhost:8083/api/categories

### Get "Animation" film category
GET http://localhost:8083/api/categories/0a0f18f2-24e9-46a7-9598-243386c6c854

###  Get unexisting film category
GET http://localhost:8083/api/categories/0a0f18f2-24e9-46a7-9598-243386c6c855

###  Create new category
PUT http://localhost:8083/api/categories/10b93e1d-fa1b-4a76-90fd-f9c7b7a3efb4
Content-Type: application/json

{
"name": "TestCategory",
"popularity": 100
}

###  Update film category
PATCH http://localhost:8083/api/categories/10b93e1d-fa1b-4a76-90fd-f9c7b7a3efb4
Content-Type: application/json

{
"popularity": 0
}

###  Delete film category with cascade
DELETE http://localhost:8083/api/categories/0a0f18f2-24e9-46a7-9598-243386c6c854

